---
title: "About This Project"
subtitle: "My journey through data visualization"
---

## About TidyTuesday

TidyTuesday is a weekly social data project that focuses on understanding how to summarize and arrange data to make meaningful and/or beautiful charts.

## My Approach

I use both **R** and **Python** to create visualizations, experimenting with different libraries and techniques. I (will) use for instance:

- **Python**: Using libraries like `pandas`, `geopandas`, `altair`, `plotnine`, and `matplotlib`
- **R**: Leveraging `ggplot2`, `tmap`, `tidyverse`, `data.table`, and various specialized packages and `ggplot2` extensions.

## Project Philosophy

Every other week, I explore the new dataset with the goal of:

1. **Creating clear visualizations** that communicate insights effectively
2. **Experimenting with techniques** to improve my data visualization skills

This is not about exploratory analyisis with meaningful insights.

## Technical Setup

This website is built with:

- **Quarto** for reproducible publishing
- **GitHub Actions** for automated deployment
- **renv** for R package management
- **uv** for Python environment management
- A custom Quarto template used through a **sh** script

The entire project is open source and available on [GitHub](https://github.com/gnoblet/TidyTuesday).


## About Me

Find my personal website [here](gnoblet.github.io)!

Feel free to explore the visualizations and reach out if you'd like to discuss or collaborate on projects!

- **GitHub**: [github.com/gnoblet/TidyTuesday](https://github.com/gnoblet/TidyTuesday)
- **Email**: gnoblet[at]zaclys.net

---